### ISSUE TITLE
Can install on Mac 10.10.5, Node.js 4.4.2 (Error: incorrect header check)

### ISSUE THREAD

**Issue by dnguyenv** [strongloop/loopback-oracle-installer#9] opened 2016-01-23 16:26 UTC
Hello,
While trying to install loopback-connector-oracle after creating a Loopback app ($ slc loopback), 
I got this problem which stops me to go further: 

$ npm install loopback-connector-oracle --save
Downloading/Extracting http://7e9918db41dd01dbf98e-ec15952f71452bc0809d79c86f5751b6.r22.cf1.rackcdn.com/loopback-oracle-MacOSX-x64-abi46-1.8.0.tar.gz
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: incorrect header check
    at Zlib._handle.onerror (zlib.js:363:17)
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "loopback-connector-oracle" "--save"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! loopback-oracle-installer@1.4.1 install: `node pkginstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the loopback-oracle-installer@1.4.1 install script 'node pkginstall.js'.
npm ERR! This is most likely a problem with the loopback-oracle-installer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node pkginstall.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls loopback-oracle-installer
npm ERR! There is likely additional logging output above.

**Comment by bnoordhuis** [comment] 2016-01-23 18:10
Is that error repeatable, i.e., does it still happen when you rerun the command?  That error message means the download is corrupt but that's usually temporal, e.g. because of a bad TCP packet.

**Comment by dnguyenv** [comment] 2016-01-23 21:49
Yes @bnoordhuis , it always happens for me. My environment: Mac 10.10.5, Node 4.2.2

**Comment by bnoordhuis** [comment] 2016-01-24 12:15
I'm going to defer to @raymondfeng or @rmg here.  I can reproduce the error now; the rackcdn.com URL sometimes fails with 502 Bad Gateway, sometimes with 404 Not Found.

**Comment by raymondfeng** [comment] 2016-01-24 17:31
The prebuilt driver for Node 4.2.2 (abi46) was missing. I just uploaded one. The problem should be fixed now.

**Closed by raymondfeng** 2016-01-24 17:31 UTC

**Comment by dnguyenv** [comment] 2016-01-26 17:05
Thanks @raymondfeng looks like it's working on my Mac with Node 4.2.2 now.
